<?xml version="1.0"?>

<robot name="robaato" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.141592653589793"/>

  <xacro:property name="chassis_x" value="0.38000"/>
  <xacro:property name="chassis_y" value="0.31400"/>
  <xacro:property name="chassis_z" value="0.11900"/>
  <xacro:property name="chassis_w" value="1.00000"/>

  <xacro:property name="wheel_r" value="0.0350"/>
  <xacro:property name="wheel_d" value="0.0240"/>
  <xacro:property name="wheel_w" value="0.2000"/>

  <xacro:property name="wheel_dx" value="0.04848"/>
  <xacro:property name="wheel_dy" value="0.00850"/>
  <xacro:property name="wheel_dz" value="0.01220"/>

  <xacro:property name="caster_r" value="${wheel_r-wheel_dz}"/>

  <xacro:property name="tof_x" value="0.00300"/>
  <xacro:property name="tof_y" value="0.03000"/>
  <xacro:property name="tof_z" value="0.20000"/>
  <xacro:property name="tof_h" value="${0.8*tof_z}"/>
  <xacro:property name="tof_w" value="0.00500"/>

  <xacro:property name="tof_scan_angle" value="${PI/12}"/>
  <xacro:property name="tof_dist_min" value="0.0005"/>
  <xacro:property name="tof_dist_max" value="1.0000"/>
  <xacro:property name="tof_linear_res" value="0.01"/>

  <xacro:property name="sensor_update_rate" value="10"/>
  <xacro:property name="actuator_update_rate" value="20"/>

</robot>
